# We need to do three things in this file: edit the config file, add that new file to git, and open the PR. 
name: Repository Dispatch Receiver 
on:
  repository_dispatch:
    types: [new-project]
jobs:
  # edit_config_file:
    # This is where we receive github.event.client_payload.project_name. 
    # Once we get it we want to run the script that allows us to access the file system
    # to edit the config file. The example for this repo is a .json file we need to parse, edit, then 
    # write back to the file system
    # If we want 
  # add_file_to_git:
    # This is where we add the file to git. This could be taken care of in the first job?
  create_pull_request:
    runs-on: ubuntu-latest
    needs: getConfigFile
    if: ${{needs.getConfigFile.outputs.file}}
    steps:
      - uses: actions/checkout@v2 
      - name: "Create PR"
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: "Adds new project"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: 'Adds new project: ${{ github.event.client_payload.project_name }}'
          body: |
            This adds the new project `${{ github.event.client_payload.project_name }}` module to new to `${{needs.filesChanged.outputs.configFile}}`
          draft: true
          delete-branch: true 
          branch: ${{github.actor}}/add-${{ github.event.client_payload.project_name }}-project


