name: Repository Dispatch Receiver 
on:
  repository_dispatch:
    types: [new-project]
jobs:
  # This name could be changed
  getConfigFile:
    runs-on: ubuntu-latest
    outputs:
      file: ${{ steps.set_output_config.outputs.file }}
    env:
      PREV_COMMIT: echo "git rev-parse @~ | xargs"
    steps:    
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: set_output_config
        uses: technote-space/get-diff-action@v5
        with:
          FILES: project.json
      - name: Check files 
        run: echo ${{env.MATCHED_FiLES}}

  createPullRequest:
    runs-on: ubuntu-latest
    needs: getConfigFile
    if: ${{needs.getConfigFile.outputs.file}}
    steps:
      - uses: actions/checkout@v2 
      - name: "Test"
        run: echo ${{needs.getConfigFile.outputs.file}}
    # steps:
    #   - uses: actions/checkout@v2 
    #   - name: "Create PR"
    #     id: cpr
    #     uses: peter-evans/create-pull-request@v3
    #     with:
    #       token: ${{ secrets.PAT }}
    #       commit-message: "Adds new project"
    #       committer: GitHub <noreply@github.com>
    #       author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
    #       title: 'Adds new project: ${{ github.event.client_payload.project_name }}'
    #       body: |
    #         This adds the new project `${{ github.event.client_payload.project_name }}` module to new to `${{needs.filesChanged.outputs.configFile}}`
    #       draft: true
    #       delete-branch: true 
    #       branch: ${{github.actor}}/add-${{ github.event.client_payload.project_name }}-project


