name: Repository Dispatch Receiver 
on:
  repository_dispatch:
    types: [new-project]
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.event.client_payload.message }}
  filesChanged:
    runs-on: ubuntu-latest

    steps:
      - name: Get changed files
        id: changes
        uses: actions/checkout@v2  
        with: 
          fetch-depth: 0
      - run: echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})" >> $GITHUB_ENV


  # createPullRequest:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2 
  #     - name: "Create PR"
  #       id: cpr
  #       uses: peter-evans/create-pull-request@v3
  #       with:
  #         token: ${{ secrets.PAT }}
  #         commit-message: "Adds new project"
  #         committer: GitHub <noreply@github.com>
  #         author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
  #         title: 'Adds new project: ${{ github.event.client_payload.project_name }}'
  #         body: |
  #           This adds the new project `${{ github.event.client_payload.project_name }}` module to new to `${{needs.filesChanged.outputs.configFile}}`
  #         draft: true
  #         delete-branch: true 
  #         branch: ${{github.actor}}/add-${{ github.event.client_payload.project_name }}-project


