name: Repository Dispatch Receiver 
on:
  repository_dispatch:
    types: [new-project]
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.event.client_payload.message }}
  name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
   with:
          token: ${{ secrets.PAT }}
          committer: GitHub <noreply@github.com>
          commit-message: Adds a new project
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: 'Adding new project ${{ github.event.client_payload.project_name }}'
          body: |
            This handles adding ${{ github.event.client_payload.project_name }} to the proper config file