name: Repository Dispatch Receiver 
on:
  repository_dispatch:
    types: [new-project]
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.event.client_payload.message }}
  changedfiles:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all}}
      configFile: ${{ steps.changes.outputs.configFile }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
     
      - name: Get changed files
        id: changes
        with:
          fetch-depth: 0
          run: |
            echo "::set-output name=configFile::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep project.json | xargs)" \
            echo ${{changedfiles.outputs.configFile}}

  createPullRequest:
    runs-on: ubuntu-latest
    needs: changedfiles
    if: ${{needs.changedfiles.outputs.configFile}}
    steps:
      - uses: actions/checkout@v2 
      - name: "Test"
        run: echo "this worked"
    # steps:
    #   - uses: actions/checkout@v2 
    #   - name: "Create PR"
    #     id: cpr
    #     uses: peter-evans/create-pull-request@v3
    #     with:
    #       token: ${{ secrets.PAT }}
    #       commit-message: "Adds new project"
    #       committer: GitHub <noreply@github.com>
    #       author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
    #       title: 'Adds new project: ${{ github.event.client_payload.project_name }}'
    #       body: |
    #         This adds the new project `${{ github.event.client_payload.project_name }}` module to new to `${{needs.filesChanged.outputs.configFile}}`
    #       draft: true
    #       delete-branch: true 
    #       branch: ${{github.actor}}/add-${{ github.event.client_payload.project_name }}-project


