name: Repository Dispatch Receiver 
on:
  repository_dispatch:
    types: [new-project]
jobs:
  # This name could be changed
  edit_config_file:
    runs-on: ubuntu-latest
    outputs:
      file: ${{ steps.set_output_config.outputs.file }}
    steps: 
    - uses: actions/checkout@v2
    - name: Setup node 
    - uses: actions/setup-node@v2
      with: 
          node-version: '14'
    - name: Edit project config file 
    - run: node 2 + 2
      # run: node ./.github/workflows/update-config.js ${{context.payload.client_payload.project_name}}
  createPullRequest:
    runs-on: ubuntu-latest
    needs: getConfigFile
    if: ${{needs.getConfigFile.outputs.file}}
    steps:
      - uses: actions/checkout@v2 
      - name: "Create PR"
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: "Adds new project"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: 'Adds new project: ${{ github.event.client_payload.project_name }}'
          body: |
            This adds the new project `${{ github.event.client_payload.project_name }}` module to new to `${{needs.filesChanged.outputs.configFile}}`
          draft: true
          delete-branch: true 
          branch: ${{github.actor}}/add-${{ github.event.client_payload.project_name }}-project


